### PR TITLE
Add ES5 compatibility

### PR DESCRIPTION
**Pull request by fregante**

### CODE REVIEW

**Comment by SimonSchick** [comment]
Is there a specific reason you need es5 compability?
I'm not really a fan of _downgrading_ my package.

**Comment by fregante** [comment]
Because I use it on the client and babel isn't applied to what's in node_modules with browserify. I'm not a fan either but currently I had to download the .js file manually and keep it outside node_modules like a Neanderthal. 😅 Arrow functions aren't supported even in the latest Safari :(

**Comment by SimonSchick** [comment]
Have you tried changing you babel config instead?
https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed

**Comment by fregante** [comment]
It's not a good idea to run transforms on code I don't own because it might break. This PR is a safer change that just works, everywhere and for everyone, including node 0.12

**Comment by fregante** [comment]
It's ok if you don't feel comfortable pulling it in, I'd use https://github.com/timse/polling-for-attention which has a build step

**Pull request closed without merging**
