### PR TITLE
Type definitions for TypeScript

### PR DESCRIPTION
**Pull request by MyRedDice**

### CODE REVIEW

**Comment by SimonSchick** [comment]
Hey, thanks for the PR.

I was actually looking into porting this package to TS myself a while ago.

Unfortunately I ran into the same generic problem you ran into (I think).

I sort of solved it by making the result of `use` generic:

(Please note that breaking changes here are intentional, for now).

```typescript
export interface PromiseCtor<I> {
	new <T>(executor: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): I;
}

export type Condition<V> = () => V | void;

/**
 * Note: These are declared so we don't depend on dom/node typings.
 */
export type Interval = any;
declare function setInterval(fn: () => void, timeout?: number): Interval;
declare function clearInterval(interval: Interval): void;

/**
 * Waits for the condition function to return a truthy value.
 * @param Promise An ES6-compatible Promise implementation.
 * @param condition The function that will be called to check the condition.
 * @param interval The interval in which to check the condition.
 * @return Resolves what the either condition or value function returned.
 */
function waitForFn<V, I extends PromiseLike<V>>(Promise: PromiseCtor<I>, condition: Condition<V>, interval = 50) {
	return new Promise((resolve, reject) => {
		const int = setInterval(() => {
			try {
				const isDone = condition();
				// REVIEW: Breaking change, is this a good thing to do?
				if (isDone !== undefined) {
					clearInterval(int);
					resolve(isDone);
				}
			} catch (error) {
				clearInterval(int);
				reject(error);
			}
		}, interval);
	});
}

/**
 * Binds waitFor to the specified promise implementation.
 * @param Promise The promise constructor.
 * @return Returns the bound waitFor function.
 */
export function use<V, I extends PromiseLike<V>>(Promise: PromiseCtor<I>) {
	// manual bind to preserve type info
	return (condition: Condition<V>, interval?: number) => {
		return waitForFn(Promise, condition, interval);
	}
}

// We intentionally declare the specific type of `waitFor` here to retain genericity of the promise return type.

/**
 * waitFor using native promise implementation.
 */
export const waitFor: <V>(condition: Condition<V>, interval?: number) => Promise<V> = use(Promise);
```

Usage would look like this:

```typescript
// Explicitly declare function type once.
const myWaitFor: <V>(condition: Condition<V>, interval?: number) => MyImpl<V> = use(MyImpl);
const myProm = myWaitFor(() => true);
```

I think both of these are _acceptable_ solutions, thoughts?

**Comment by MyRedDice** [comment]
I agree. A one-line typedec after the import isn't ideal, but is worth it for getting types. And your native TS code is cleaner than the shenanigans needed to get it working with index.d.ts. I can close this PR.

I wonder if promise-waitfor could pre-declare a few waitFors using common promise libraries to save the one-line. Eg, waitFor.jQuery, waitFor.BlueBird, etc. There are only so many promise libraries out there. Each would need its own file, I imagine.

**Comment by SimonSchick** [comment]
I'd rather not depend on various other `@types` libraries.

**Comment by SimonSchick** [comment]
I'll do a release around tomorrow.

**Pull request closed without merging**
